%Krupsona (Greek Hideout) Land Generation
%TechChariot
%9.15.22

clear all
close all
clc


tic
disp(["Run Executed " datestr(clock) "..."])

filestruc = dir; %Extract a structure of the files in this directory
path = filestruc.folder; path = path(1:90); addpath(genpath(path)) %Adding functions in main folder to the path
files = {filestruc.name}; [filename] = RMS_GetLatest(files,'rms');
[Preface,LPM_exp,~] = RMS_Manual_Land(filename);

MLA = [{'L { terrain_type BT land_percent 100 land_position  1  1 }'}; ...
       {'L { terrain_type BT land_percent 100 land_position  1 99 }'}; ...
       {'L { terrain_type BT land_percent 100 land_position 99  1 }'}; ...
       {'L { terrain_type BT land_percent 100 land_position 99 99 }'}];

%for i = 1:80
%MLA = [MLA; {'L { terrain_type MF base_size 1 number_of_tiles 49 min_placement_distance 4 left_border 15 right_border 15 top_border 15 bottom_border 15 }' }];
%end
%%

%MLP = [{'L { terrain_type MF base_size 0 land_percent 100 land_position 50 50 }'}];
MLP = [];

MLP = [MLP; ...
      {'create_player_lands'}; ...
      {'{'}; ...
      {'terrain_type Y'}; ...
      {'base_elevation 0'}; ...
      {'clumping_factor 30'}; ...
      {'other_zone_avoidance_distance 6'}; ...
      {'if TINY_MAP'}; ...
      {'circle_radius 24 0'};
      {'base_size 12'}; ...
      {'elseif SMALL_MAP'}; ...
      {'circle_radius 25 0'}; ...
      {'base_size 13'}; ...
      {'elseif MEDIUM_MAP'}; ...
      {'circle_radius 26 0'}; ...
      {'base_size 14'}; ...
      {'elseif LARGE_MAP'}; ...
      {'circle_radius 27 0'}; ...
      {'base_size 14'}; ...
      {'elseif HUGE_MAP'}; ...
      {'circle_radius 28 0'}; ...
      {'base_size 14'}; ...
      {'elseif GIGANTIC_MAP'}; ...
      {'circle_radius 28 0'}; ...
      {'base_size 14'}; ...
      {'else'}; ...
      {'endif'}; ...
      {'if LOW_RESOURCES'}; ...
      {'base_size 0'}; ...
      {'land_percent 0'}; ...
      {'else'}; ...
      {'land_percent 100'}; ...
      {'endif'}; ...
      {'}'}];


Config = [{1}]; k = 1;
for i = 1:length(Config)
R1 = []; R2 = R1;
for j = 1:360
R1 = [R1; LandScribeV5([{'G'}],[{0}],{00 00},{j-1},{'0*x'},{1},{0},[30 32])]; %Field Circle Generation
R2 = [R2; LandScribeV5([{'R'}],[{0}],{00 00},{j-1},{'0*x'},{1},{0},[33 43])]; %Field Circle Generation
end
%
FC = [R1; R2];
[COMMAND(k).XY] = [RMS_Processor_V4([FC],LPM_exp)];
k = k + 1;
end
%

[List] = RMS_RS_V2(Config,{'C'},COMMAND);


CODE = [Preface; MLP; List; MLA]; %Adding Preface, Definitions, Random Statement to beginning of CODE

RMS_ForgeV4(filename,CODE);

disp(["Run Completed " datestr(clock) "..."])
toc


%ObjectAutoscribeV9('Kresphugeto.ods')
